# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Setting
locale: "zh-CN"
title: "pezy's stack"
title_separator: "|"
name: "pezy"
description: "push my mind to stack."
url: "https://pushmind.org"
reposiory: "pezy/pushmind"

comments:
    provider: "staticman"
staticman:
    allowedFields: ["name", "email", "url", "message"]
    branch: "master"
    commitMessage: "New comment."
    filename: comment-{@timestamp}
    format: "yml"
    moderation: true
    path: "_data/comments/{options.slug}"
    requiredFields: ["name", "email", "message"]
    transforms:
        email: "md5"
    generatedField:
        date:
            type: "date"
            options:
                format: "timestamp-seconds"

og_image: /assets/images/site-logo.png

# Outputting
permalink: /:categories/:title/
breadcrumbs: true
paginate: 5
paginate_path: /page:num/

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      comments: true
      share: true
      related: true

# Site Author
author:
  name: "pezy"
  avatar: "/assets/avatar.png"
  bio: "Software engineer | C/C++ | Qt | Geophysics | Computer Graphics | Front-end | Python"
  location: "Beijing, China"
  stackoverflow: "1155235/pezy"
  url: "https://pushmind.org"

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
    clippings: all
    ignore:
        envs: development
